spring:
  application:
    name: coordinate-service
  config:
    import:
      - nacos:coordinate-service.yaml
      - nacos:kafka.yaml
      - nacos:logging.yml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.186:8848
      config:
        server-addr: 192.168.0.186:8848
        file-extension: yaml
        group: DEFAULT_GROUP
